// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Q9rk78y9Hv7Do6mcsiEQJidE29NbsP4',
    appId: '1:1068722394548:web:6811b0bc0c8a341c968ee1',
    messagingSenderId: '1068722394548',
    projectId: 'my-wallet-c0aea',
    authDomain: 'my-wallet-c0aea.firebaseapp.com',
    storageBucket: 'my-wallet-c0aea.firebasestorage.app',
    measurementId: 'G-0Y2D1RLVJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67WNUh6LjCdWXdSInEm-l6I8U_rXs9uU',
    appId: '1:1068722394548:android:c2a87216c76a454f968ee1',
    messagingSenderId: '1068722394548',
    projectId: 'my-wallet-c0aea',
    storageBucket: 'my-wallet-c0aea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_X-JfPWkkp3Lu-1Bwry9Gk1WVZreRus',
    appId: '1:1068722394548:ios:2a3e72d94c26d9c6968ee1',
    messagingSenderId: '1068722394548',
    projectId: 'my-wallet-c0aea',
    storageBucket: 'my-wallet-c0aea.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_X-JfPWkkp3Lu-1Bwry9Gk1WVZreRus',
    appId: '1:1068722394548:ios:2a3e72d94c26d9c6968ee1',
    messagingSenderId: '1068722394548',
    projectId: 'my-wallet-c0aea',
    storageBucket: 'my-wallet-c0aea.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Q9rk78y9Hv7Do6mcsiEQJidE29NbsP4',
    appId: '1:1068722394548:web:880ea5d3d1175bff968ee1',
    messagingSenderId: '1068722394548',
    projectId: 'my-wallet-c0aea',
    authDomain: 'my-wallet-c0aea.firebaseapp.com',
    storageBucket: 'my-wallet-c0aea.firebasestorage.app',
    measurementId: 'G-BBTV896633',
  );
}
